[build]
  publish = "public"
  command = "npm i -g postcss-cli && npm i && hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.71"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm i -g postcss-cli && npm i && hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.71"