[build]
  publish = "public"
  command = "npm i -g postcss postcss-cli && npm i && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.106.0"
  HUGO_ENABLEGITINFO = "true"
  RUBY_VERSION = "2.6.2"
  NODE_VERSION = "18.5.0"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm i -g postcss postcss-cli && npm i && hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
