[build]
publish = "public"
command = "npm i -g postcss-cli && npm i && hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.51"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm i -g postcss-cli && npm i && hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.51"